const mongoose = require('mongoose');
const Weapons = require('./models/weapon');
const Shields = require('./models/shield');
const Helmets = require('./models/helmet');
const Chests = require('./models/chest');
const Legs = require('./models/legs');
const Rings = require('./models/ring');
const Amulets = require('./models/amulet');
const Trinkets = require('./models/trinket');
console.log('Are we feeding or are we seeding?')

mongoose.connect(`mongodb+srv://@cluster0.ivsipz0.mongodb.net/seyr?retryWrites=true&w=majority`, 
    {
    useNewUrlParser: true, useUnifiedTopology: true })
        .then(() => {
            console.log('Mongo Connection Open!');
        })
        .catch((err) => {
            console.log(err)
        });

const seedWeapons = [
    {
        name: 'Gladius',
        type: 'Short Sword',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 12,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 5,
        critical_damage: 1.3,
        dodge: 3,
        roll: 3,
        constitution: 0,
        strength: 1,
        agility: 1,
        achre: 1,
        caeren: 1,
        kyosir: 0,
        influences: ["Daethos"],
        imgURL: '/images/gladius.png'
    },
    {
        name: 'Longsword',
        type: 'Long Sword',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 12,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 5,
        critical_damage: 1.15,
        dodge: 3,
        roll: 3,
        constitution: 0,
        strength: 2,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Daethos"],
        imgURL: '/images/longsword.png'
    },
    {
        name: 'Hand Axe',
        type: 'Axe',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Blunt', 'Slash'],
        physical_damage: 12,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 7,
        critical_damage: 1.5,
        dodge: 3,
        roll: 3,
        constitution: 0,
        strength: 3,
        agility: 1,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Tshaer"],
        imgURL: '/images/handaxe.png'
    },
    {
        name: 'Scimitar',
        type: 'Curved Sword',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Blunt', 'Slash'],
        physical_damage: 12,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 10,
        critical_damage: 1.5,
        dodge: 3,
        roll: 3,
        constitution: 0,
        strength: 1,
        agility: 3,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'dyro"],
        imgURL: '/images/scimitar.png'
    },
    {
        name: 'Pugio',
        type: 'Dagger',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 6,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 7,
        critical_damage: 2.5,
        dodge: 0,
        roll: 7,
        constitution: 0,
        strength: 0,
        agility: 4,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Daethos"],
        imgURL: '/images/pugio.png'
    },
    {
        name: 'Cursed Dagger',
        type: 'Dagger',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 0,
        magical_damage: 6,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 5,
        critical_damage: 2.75,
        dodge: 0,
        roll: 7,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 4,
        caeren: 0,
        kyosir: 0,
        influences: ["Kyr'na"],
        imgURL: '/images/cursed-dagger.png'
    },
    {
        name: 'Shotel',
        type: 'Scythe',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 8,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 10,
        critical_damage: 2,
        dodge: 0,
        roll: 5,
        constitution: 0,
        strength: 2,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Ma'anre"],
        imgURL: '/images/scythe.png'
    },
    {
        name: 'Spear',
        type: 'Polearm',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce'],
        physical_damage: 12,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 7,
        critical_damage: 1.75,
        dodge: 3,
        roll: 5,
        constitution: 0,
        strength: 1,
        agility: 1,
        achre: 1,
        caeren: 1,
        kyosir: 0,
        influences: ["Daethos"],
        imgURL: '/images/spear.png'
    },
    {
        name: 'Halberd',
        type: 'Polearm',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 16,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 5,
        critical_damage: 2,
        dodge: 5,
        roll: 3,
        constitution: 0,
        strength: 2,
        agility: 4,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/halberd.png'
    },
    {
        name: 'Claymore',
        type: 'Greatsword',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Slash'],
        physical_damage: 16,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 5,
        critical_damage: 2,
        dodge: 5,
        roll: 3,
        constitution: 0,
        strength: 3,
        agility: 3,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/claymore.png'
    },
    {
        name: 'Battle Axe',
        type: 'Greataxe',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Blunt', 'Slash'],
        physical_damage: 16,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 5,
        critical_damage: 2,
        dodge: 5,
        roll: 3,
        constitution: 0,
        strength: 4,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/battleaxe.png'
    },
    {
        name: 'War Hammer',
        type: 'Greatmace',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Blunt'],
        physical_damage: 16,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 5,
        critical_damage: 2,
        dodge: 5,
        roll: 3,
        constitution: 0,
        strength: 6,
        agility: 0,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/warhammer.png'
    },
    {
        name: 'Morningstar',
        type: 'Mace',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Blunt', 'Pierce'],
        physical_damage: 8,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 7,
        critical_damage: 2,
        dodge: 3,
        roll: 5,
        constitution: 2,
        strength: 1,
        agility: 1,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/morningstar.png'
    },
    {
        name: 'Pernach',
        type: 'Mace',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Blunt'],
        physical_damage: 12,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 5,
        critical_damage: 1.5,
        dodge: 3,
        roll: 3,
        constitution: 1,
        strength: 2,
        agility: 1,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/mace.png'
    },
    {
        name: "Hand of Se'dyro",
        type: 'Mace',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Blunt'],
        physical_damage: 8,
        magical_damage: 0,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 7,
        critical_damage: 2,
        dodge: 3,
        roll: 7,
        constitution: 1,
        strength: 1,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'dyro"],
        imgURL: '/images/godHand.png'
    },
    {
        name: 'Whirlwind',
        type: 'Scythe',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 8,
        magical_damage: 8,
        physical_penetration: 0,
        magical_penetration: 0,
        critical_chance: 7,
        critical_damage: 2,
        dodge: 5,
        roll: 7,
        constitution: 0,
        strength: 2,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 2,
        influences: ["Ilios"],
        imgURL: '/images/whirlwind.png'
    },
    {
        name: 'Lava Spit',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Fire'],
        physical_damage: 0,
        magical_damage: 16,
        physical_penetration: 5,
        magical_penetration: 5,
        critical_chance: 5,
        critical_damage: 2,
        dodge: 5,
        roll: 10,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 1,
        caeren: 3,
        kyosir: 0,
        influences: ["Fyero"],
        imgURL: '/images/fire.png'
    },
    {
        name: 'Astral Spear',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Lightning'],
        physical_damage: 0,
        magical_damage: 16,
        physical_penetration: 0,
        magical_penetration: 10,
        critical_chance: 10,
        critical_damage: 1.5,
        dodge: 5,
        roll: 10,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 3,
        caeren: 1,
        kyosir: 0,
        influences: ["Astra"],
        imgURL: '/images/astral-spear.png'
    },
    {
        name: 'Caeren Barrage',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Sorcery'],
        physical_damage: 0,
        magical_damage: 9,
        physical_penetration: 0,
        magical_penetration: 10,
        critical_chance: 7,
        critical_damage: 1.5,
        dodge: 5,
        roll: 7,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 4,
        caeren: 0,
        kyosir: 0,
        influences: ["Cambire"],
        imgURL: '/images/sorcery.png'
    },
    {
        name: 'Arctic Bolt',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Frost'],
        physical_damage: 0,
        magical_damage: 12,
        physical_penetration: 10,
        magical_penetration: 10,
        critical_chance: 5,
        critical_damage: 1.5,
        dodge: 0,
        roll: 5,
        constitution: 1,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 2,
        kyosir: 2,
        influences: ["Nyrolus"],
        imgURL: '/images/frost.png'
    },
    {
        name: "Quor'ite Crush",
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Earth'],
        physical_damage: 0,
        magical_damage: 12,
        physical_penetration: 10,
        magical_penetration: 10,
        critical_chance: 5,
        critical_damage: 1.5,
        dodge: 0,
        roll: 5,
        constitution: 1,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 0,
        kyosir: 2,
        influences: ["Quor'ei"],
        imgURL: '/images/earth.png'
    },
    {
        name: "Wild",
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Wild'],
        physical_damage: 8,
        magical_damage: 8,
        physical_penetration: 5,
        magical_penetration: 5,
        critical_chance: 5,
        critical_damage: 2.5,
        dodge: 0,
        roll: 5,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 2,
        kyosir: 1,
        influences: ["Achreo"],
        imgURL: '/images/wild.png'
    },
    {
        name: 'Hush',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Righteous'],
        physical_damage: 5,
        magical_damage: 5,
        physical_penetration: 5,
        magical_penetration: 5,
        critical_chance: 5,
        critical_damage: 1.5,
        dodge: 3,
        roll: 7,
        constitution: 1,
        strength: 0,
        agility: 0,
        achre: 1,
        caeren: 2,
        kyosir: 1,
        influences: ["Daethos"],
        imgURL: '/images/faith.png'
    },
    {
        name: 'Tendril',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Spooky'],
        physical_damage: 6,
        magical_damage: 6,
        physical_penetration: 5,
        magical_penetration: 5,
        critical_chance: 5,
        critical_damage: 2,
        dodge: 3,
        roll: 7,
        constitution: 1,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 1,
        kyosir: 1,
        influences: ["Daethos"],
        imgURL: '/images/tendrils.png'
    },
    {
        name: 'Windfury',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Wind'],
        physical_damage: 0,
        magical_damage: 9,
        physical_penetration: 10,
        magical_penetration: 0,
        critical_chance: 7,
        critical_damage: 1.5,
        dodge: 3,
        roll: 7,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 4,
        kyosir: 0,
        influences: ["Ahn've"],
        imgURL: '/images/windfury.png'
    },
    {
        name: 'Longbow',
        type: 'Bow',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce'],
        physical_damage: 16,
        magical_damage: 0,
        physical_penetration: 5,
        magical_penetration: 0,
        critical_chance: 5,
        critical_damage: 2,
        dodge: 7,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 4,
        achre: 0,
        caeren: 2,
        kyosir: 0,
        influences: ["Quor'ei"],
        imgURL: '/images/bow-long.png'
    },
    {
        name: 'Reflex',
        type: 'Bow',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce'],
        physical_damage: 8,
        magical_damage: 8,
        physical_penetration: 5,
        magical_penetration: 0,
        critical_chance: 5,
        critical_damage: 2,
        dodge: 7,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 4,
        achre: 0,
        caeren: 0,
        kyosir: 2,
        influences: ["Quor'ei"],
        imgURL: '/images/bow-reflex.png'
    },
    {
        name: 'Recurve',
        type: 'Bow',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce'],
        physical_damage: 12,
        magical_damage: 4,
        physical_penetration: 5,
        magical_penetration: 0,
        critical_chance: 5,
        critical_damage: 2,
        dodge: 5,
        roll: 5,
        constitution: 0,
        strength: 0,
        agility: 4,
        achre: 2,
        caeren: 0,
        kyosir: 0,
        influences: ["Quor'ei"],
        imgURL: '/images/bow-recurve.png'
    }
];

const seedHelmets = [
    {
        name: "Knight's Helm",
        type: 'Plate-Mail',
        physical_damage: 1.05,
        magical_damage: 1,
        physical_resistance: 25,
        magical_resistance: 15,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 5,
        roll: 1,
        constitution: 4,
        strength: 3,
        agility: 0,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/knight-helm.png'
    },
    
    {
        name: 'Daethic Helm',
        type: 'Plate-Mail',
        physical_damage: 1,
        magical_damage: 1.05,
        physical_resistance: 15,
        magical_resistance: 25,
        critical_chance: 4,
        critical_damage: 1.03,
        dodge: 5,
        roll: 1,
        constitution: 2,
        strength: 2,
        agility: 0,
        achre: 0,
        caeren: 3,
        kyosir: 0,
        imgURL: '/images/daethic-helm.png'
    },
    {
        name: 'Achreon Helm',
        type: 'Leather-Mail',
        physical_damage: 1.03,
        magical_damage: 1.03,
        physical_resistance: 15,
        magical_resistance: 15,
        critical_chance: 4,
        critical_damage: 1.03,
        dodge: 3,
        roll: 3,
        constitution: 2,
        strength: 0,
        agility: 2,
        achre: 3,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/achreon-helm.png'
    },
    {
        name: 'Licivitan Helm',
        type: 'Leather-Mail',
        physical_damage: 1.03,
        magical_damage: 1.03,
        physical_resistance: 15,
        magical_resistance: 15,
        critical_chance: 4,
        critical_damage: 1.03,
        dodge: 3,
        roll: 3,
        constitution: 2,
        strength: 0,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/legion-helm.png'
    },
    {
        name: 'Ashtre Helm',
        type: 'Plate-Mail',
        physical_damage: 1.03,
        magical_damage: 1.03,
        physical_resistance: 20,
        magical_resistance: 20,
        critical_chance: 4,
        critical_damage: 1.03,
        dodge: 5,
        roll: 1,
        constitution: 0,
        strength: 2,
        agility: 2,
        achre: 1,
        caeren: 2,
        kyosir: 0,
        imgURL: '/images/ashtre-helm.png'
    },
    {
        name: 'Chain-Knight Helm',
        type: 'Chain-Mail',
        physical_damage: 1.05,
        magical_damage: 1,
        physical_resistance: 20,
        magical_resistance: 15,
        critical_chance: 8,
        critical_damage: 1.03,
        dodge: 5,
        roll: 3,
        constitution: 2,
        strength: 3,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/chain-helm.png'
    },
    {
        name: 'Fang Helm',
        type: 'Chain-Mail',
        physical_damage: 1.07,
        magical_damage: 0.96,
        physical_resistance: 20,
        magical_resistance: 20,
        critical_chance: 4,
        critical_damage: 1.1,
        dodge: 5,
        roll: 3,
        constitution: 0,
        strength: 5,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/fang-helm.png'
    },
    {
        name: 'Fireland Helm',
        type: 'Plate-Mail',
        physical_damage: 1.05,
        magical_damage: 1,
        physical_resistance: 25,
        magical_resistance: 15,
        critical_chance: 8,
        critical_damage: 1.15,
        dodge: 5,
        roll: 1,
        constitution: 0,
        strength: 0,
        agility: 2,
        achre: 1,
        caeren: 0,
        kyosir: 1,
        imgURL: '/images/fireland-helm.png'
    },
    {
        name: "Marauder's Helm",
        type: 'Leather-Mail',
        physical_damage: 1.07,
        magical_damage: 0.96,
        physical_resistance: 15,
        magical_resistance: 10,
        critical_chance: 6,
        critical_damage: 1.05,
        dodge: 3,
        roll: 3,
        constitution: 0,
        strength: 2,
        agility: 5,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/marauder-helm.png'
    },
    {
        name: 'Soverain Helm',
        type: 'Plate-Mail',
        physical_damage: 1,
        magical_damage: 1.05,
        physical_resistance: 15,
        magical_resistance: 25,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 5,
        roll: 1,
        constitution: 3,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 2,
        kyosir: 0,
        imgURL: '/images/soverain-helm.png'
    },
    {
        name: 'Occult Mask',
        type: 'Leather-Mail',
        physical_damage: 1.03,
        magical_damage: 1.03,
        physical_resistance: 15,
        magical_resistance: 25,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 3,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 3,
        caeren: 3,
        kyosir: 1,
        imgURL: '/images/occult-helm.png'
    },
    {
        name: 'Fyers Hood',
        type: 'Leather-Cloth',
        physical_damage: 0.96,
        magical_damage: 1.07,
        physical_resistance: 5,
        magical_resistance: 15,
        critical_chance: 4,
        critical_damage: 1.1,
        dodge: 1,
        roll: 5,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 5,
        kyosir: 2,
        imgURL: '/images/fyers-hood.png'
    },
    {
        name: 'Astral Hood',
        type: 'Leather-Cloth',
        physical_damage: 0.96,
        magical_damage: 1.07,
        physical_resistance: 5,
        magical_resistance: 15,
        critical_chance: 6,
        critical_damage: 1.05,
        dodge: 1,
        roll: 5,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 5,
        caeren: 0,
        kyosir: 2,
        imgURL: '/images/astral-hood.png'
    },
    {
        name: 'Dae Hood',
        type: 'Leather-Cloth',
        physical_damage: 1.03,
        magical_damage: 1.03,
        physical_resistance: 10,
        magical_resistance: 15,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 1,
        roll: 5,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 1,
        caeren: 3,
        kyosir: 1,
        imgURL: '/images/dae-hood.png'
    },
    {
        name: 'Sage Hood',
        type: 'Leather-Cloth',
        physical_damage: 1,
        magical_damage: 1.04,
        physical_resistance: 10,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 1,
        roll: 5,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 3,
        caeren: 2,
        kyosir: 0,
        imgURL: '/images/sage-hood.png'
    },
    {
        name: "Quor'ite Hood",
        type: 'Leather-Cloth',
        physical_damage: 1.03,
        magical_damage: 1.03,
        physical_resistance: 15,
        magical_resistance: 15,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 1,
        roll: 5,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 3,
        caeren: 0,
        kyosir: 2,
        imgURL: '/images/earth-hood.png'
    },
];

const seedChests = [
    {
        name: "Knight's Cuirass",
        type: 'Plate-Mail',
        physical_damage: 1.04,
        magical_damage: 1,
        physical_resistance: 20,
        magical_resistance: 10,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 7,
        roll: 3,
        constitution: 3,
        strength: 2,
        agility: 0,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/knight-armor.png'
    },
    {
        name: 'Daethic Cuirass',
        type: 'Plate-Mail',
        physical_damage: 1,
        magical_damage: 1.04,
        physical_resistance: 10,
        magical_resistance: 20,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 7,
        roll: 3,
        constitution: 1,
        strength: 2,
        agility: 0,
        achre: 0,
        caeren: 2,
        kyosir: 0,
        imgURL: '/images/daethic-armor.png'
    },
    {
        name: 'Achreon Armor',
        type: 'Leather-Mail',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 10,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.02,
        dodge: 5,
        roll: 5,
        constitution: 2,
        strength: 0,
        agility: 1,
        achre: 2,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/achreon-armor.png'
    },
    {
        name: 'Licivitan Cuirass',
        type: 'Leather-Mail',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 10,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.02,
        dodge: 5,
        roll: 5,
        constitution: 2,
        strength: 0,
        agility: 2,
        achre: 0,
        caeren: 1,
        kyosir: 0,
        imgURL: '/images/daethic-armor.png'
    },
    {
        name: 'Ashtre Armor',
        type: 'Plate-Mail',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 15,
        magical_resistance: 15,
        critical_chance: 3,
        critical_damage: 1.02,
        dodge: 7,
        roll: 3,
        constitution: 0,
        strength: 2,
        agility: 1,
        achre: 1,
        caeren: 1,
        kyosir: 0,
        imgURL: '/images/ashtre-armor.png'
    },
    {
        name: 'Chain-Knight Cuirass',
        type: 'Chain-Mail',
        physical_damage: 1.04,
        magical_damage: 1,
        physical_resistance: 15,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 7,
        roll: 5,
        constitution: 1,
        strength: 2,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/chain-armor.png'
    },
    {
        name: 'Fang Armor',
        type: 'Chain-Mail',
        physical_damage: 1.05,
        magical_damage: 0.97,
        physical_resistance: 15,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 7,
        roll: 5,
        constitution: 0,
        strength: 3,
        agility: 0,
        achre: 2,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/fang-armor.png'
    },
    {
        name: 'Fireland Cuirass',
        type: 'Plate-Mail',
        physical_damage: 1.04,
        magical_damage: 1,
        physical_resistance: 15,
        magical_resistance: 15,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 7,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 2,
        achre: 2,
        caeren: 0,
        kyosir: 1,
        imgURL: '/images/fireland-armor.png'
    },
    {
        name: "Marauder's Armor",
        type: 'Leather-Mail',
        physical_damage: 1.05,
        magical_damage: 0.97,
        physical_resistance: 15,
        magical_resistance: 5,
        critical_chance: 4,
        critical_damage: 1.05,
        dodge: 5,
        roll: 5,
        constitution: 0,
        strength: 2,
        agility: 3,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/marauder-armor.png'
    },
    {
        name: 'Soverain Cuirass',
        type: 'Plate-Mail',
        physical_damage: 1,
        magical_damage: 1.04,
        physical_resistance: 10,
        magical_resistance: 20,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 7,
        roll: 3,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 1,
        caeren: 2,
        kyosir: 0,
        imgURL: '/images/soverain-armor.png'
    },
    {
        name: 'Occult Armor',
        type: 'Leather-Mail',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 10,
        magical_resistance: 10,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 5,
        roll: 5,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 3,
        kyosir: 0,
        imgURL: '/images/occult-armor.png'
    },  
    {
        name: 'Fyers Robes',
        type: 'Leather-Cloth',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_resistance: 5,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.07,
        dodge: 3,
        roll: 7,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 4,
        caeren: 0,
        kyosir: 1,
        imgURL: '/images/fyers-robes.png'
    },
    {
        name: 'Astral Robes',
        type: 'Leather-Cloth',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_resistance: 5,
        magical_resistance: 10,
        critical_chance: 4,
        critical_damage: 1.05,
        dodge: 3,
        roll: 7,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 4,
        caeren: 0,
        kyosir: 1,
        imgURL: '/images/astral-robes.png'
    },
    {
        name: 'Dae Robes',
        type: 'Leather-Cloth',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 5,
        magical_resistance: 15,
        critical_chance: 3,
        critical_damage: 1.02,
        dodge: 3,
        roll: 7,
        constitution: 1,
        strength: 0,
        agility: 0,
        achre: 1,
        caeren: 2,
        kyosir: 1,
        imgURL: '/images/dae-robes.png'
    },
    {
        name: 'Sage Robes',
        type: 'Leather-Cloth',
        physical_damage: 1,
        magical_damage: 1.04,
        physical_resistance: 8,
        magical_resistance: 8,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 1,
        roll: 9,
        constitution: 1,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 2,
        kyosir: 0,
        imgURL: '/images/sage-robes.png'
    },
    {
        name: "Quor'ite Robes",
        type: 'Leather-Cloth',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 10,
        magical_resistance: 10,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 1,
        roll: 9,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 0,
        kyosir: 1,
        imgURL: '/images/earth-robes.png'
    },
];

const seedLegs = [
    {
        name: "Knight's Greaves",
        type: 'Plate-Mail',
        physical_damage: 1.03,
        magical_damage: 1,
        physical_resistance: 15,
        magical_resistance: 10,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 3,
        roll: 0,
        constitution: 1,
        strength: 1,
        agility: 0,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/knight-legs.png'
    },
    {
        name: 'Daethic Greaves',
        type: 'Plate-Mail',
        physical_damage: 1,
        magical_damage: 1.03,
        physical_resistance: 10,
        magical_resistance: 15,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 3,
        roll: 0,
        constitution: 1,
        strength: 1,
        agility: 0,
        achre: 0,
        caeren: 1,
        kyosir: 0,
        imgURL: '/images/daethic-legs.png'
    },
    {
        name: 'Achreon Greaves',
        type: 'Leather-Mail',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 10,
        magical_resistance: 5,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 1,
        roll: 1,
        constitution: 1,
        strength: 0,
        agility: 1,
        achre: 1,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/achreon-legs.png'
    },
    {
        name: 'Licivitan Greaves',
        type: 'Leather-Mail',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 8,
        magical_resistance: 8,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 1,
        roll: 1,
        constitution: 1,
        strength: 0,
        agility: 1,
        achre: 0,
        caeren: 1,
        kyosir: 0,
        imgURL: '/images/daethic-legs.png'
    },
    {
        name: 'Ashtre Greaves',
        type: 'Plate-Mail',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 15,
        magical_resistance: 10,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 3,
        roll: 0,
        constitution: 0,
        strength: 1,
        agility: 0,
        achre: 1,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/ashtre-legs.png'
    },
    {
        name: 'Chain-Knight Greaves',
        type: 'Chain-Mail',
        physical_damage: 1.03,
        magical_damage: 1,
        physical_resistance: 15,
        magical_resistance: 5,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 3,
        roll: 1,
        constitution: 0,
        strength: 1,
        agility: 1,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/chain-legs.png'
    },
    {
        name: 'Fang Greaves',
        type: 'Chain-Mail',
        physical_damage: 1.05,
        magical_damage: 0.97,
        physical_resistance: 10,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.02,
        dodge: 3,
        roll: 1,
        constitution: 0,
        strength: 2,
        agility: 0,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/fang-legs.png'
    },
    {
        name: 'Fireland Greaves',
        type: 'Plate-Mail',
        physical_damage: 1.03,
        magical_damage: 1,
        physical_resistance: 15,
        magical_resistance: 10,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 3,
        roll: 0,
        constitution: 0,
        strength: 0,
        agility: 2,
        achre: 1,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/fireland-legs.png'
    },
    {
        name: "Marauder's Greaves",
        type: 'Leather-Mail',
        physical_damage: 1.05,
        magical_damage: 0.97,
        physical_resistance: 10,
        magical_resistance: 5,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 1,
        roll: 1,
        constitution: 0,
        strength: 2,
        agility: 1,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/marauder-legs.png'
    },
    {
        name: 'Soverain Greaves',
        type: 'Plate-Mail',
        physical_damage: 1,
        magical_damage: 1.03,
        physical_resistance: 10,
        magical_resistance: 15,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 3,
        roll: 0,
        constitution: 1,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 1,
        kyosir: 0,
        imgURL: '/images/soverain-legs.png'
    },
    {
        name: 'Occult Greaves',
        type: 'Leather-Mail',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 8,
        magical_resistance: 8,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 1,
        roll: 1,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 2,
        kyosir: 0,
        imgURL: '/images/occult-legs.png'
    },  
    {
        name: 'Fyers Pants',
        type: 'Leather-Cloth',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_resistance: 0,
        magical_resistance: 10,
        critical_chance: 2,
        critical_damage: 1.05,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 3,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/fyers-legs.png'
    },
    {
        name: 'Astral Pants',
        type: 'Leather-Cloth',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_resistance: 0,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 3,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/astral-legs.png'
    },
    {
        name: 'Dae Pants',
        type: 'Leather-Cloth',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 5,
        magical_resistance: 10,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 0,
        roll: 3,
        constitution: 1,
        strength: 0,
        agility: 0,
        achre: 1,
        caeren: 1,
        kyosir: 0,
        imgURL: '/images/dae-legs.png'
    },
    {
        name: 'Sage Pants',
        type: 'Leather-Cloth',
        physical_damage: 1,
        magical_damage: 1.03,
        physical_resistance: 5,
        magical_resistance: 5,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 1,
        kyosir: 0,
        imgURL: '/images/sage-legs.png'
    },
    {
        name: "Quor'ite Pants",
        type: 'Leather-Cloth',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 8,
        magical_resistance: 8,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 0,
        roll: 3,
        constitution: 1,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/earth-legs.png'
    },
];

const seedShields = [
    {
        name: 'Parrying Buckler',
        type: 'Small Shield',
        physical_damage: 1.04,
        magical_damage: 1.04,
        physical_resistance: 5,
        magical_resistance: 5,
        critical_chance: 5,
        critical_damage: 1,
        dodge: 0,
        roll: 6,
        constitution: 0,
        strength: 0,
        agility: 2,
        achre: 2,
        caeren: 0,
        kyosir: 2,
        imgURL: '/images/buckler.png'
    },
    {
        name: 'Heater',
        type: 'Medium Shield',
        physical_damage: 1.03,
        magical_damage: 1.03,
        physical_resistance: 10,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1,
        dodge: 2,
        roll: 4,
        constitution: 2,
        strength: 2,
        agility: 0,
        achre: 0,
        caeren: 2,
        kyosir: 0,
        imgURL: '/images/heater-shield.png'
    },
    {
        name: 'Scutum',
        type: 'Large Shield',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_resistance: 20,
        magical_resistance: 20,
        critical_chance: 3,
        critical_damage: 1,
        dodge: 4,
        roll: 2,
        constitution: 2,
        strength: 0,
        agility: 2,
        achre: 0,
        caeren: 2,
        kyosir: 0,
        imgURL: '/images/scutum.png'
    },
    {
        name: 'Pavise',
        type: 'Great Shield',
        physical_damage: 1,
        magical_damage: 1,
        physical_resistance: 30,
        magical_resistance: 30,
        critical_chance: 3,
        critical_damage: 1,
        dodge: 6,
        roll: 0,
        constitution: 1,
        strength: 1,
        agility: 1,
        achre: 1,
        caeren: 1,
        kyosir: 1,
        imgURL: '/images/pavise.png'
    }
];

const seedRings = [
    {
        name: "Knight's Ring",
        type: 'Magic',
        physical_damage: 1.03,
        magical_damage: 1,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 0,
        roll: 3,
        constitution: 3,
        strength: 2,
        agility: 0,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/knight-ring.png'
    },
    {
        name: "Ashtre Ring",
        type: 'Magic',
        physical_damage: 1.05,
        magical_damage: 0.97,
        physical_penetration: 5,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 2,
        agility: 2,
        achre: 1,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/ashtre-ring.png'
    },
    {
        name: 'Soverain Ring',
        type: 'Magic',
        physical_damage: 1,
        magical_damage: 1.03,
        physical_penetration: 5,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 3,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 3,
        kyosir: 0,
        imgURL: '/images/soverain-ring.png'
    },
    {
        name: 'Daethic Ring',
        type: 'Magic',
        physical_damage: 1.03,
        magical_damage: 1,
        physical_penetration: 2,
        magical_penetration: 2,
        physical_resistance: 2,
        magical_resistance: 2,
        critical_chance: 2,
        critical_damage: 1.05,
        dodge: 0,
        roll: 2,
        constitution: 1,
        strength: 1,
        agility: 1,
        achre: 1,
        caeren: 1,
        kyosir: 0,
        imgURL: '/images/daethic-ring.png'
    },
    {
        name: 'Achreon Ring',
        type: 'Magic',
        physical_damage: 1.05,
        magical_damage: 0.97,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 5,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 5,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/achre-ring.png'
    },
    {
        name: 'Cambiren Ring',
        type: 'Magic',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 3,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 5,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 5,
        kyosir: 0,
        imgURL: '/images/caeren-ring.png'
    },
    {
        name: 'Sage Ring',
        type: 'Magic',
        physical_damage: 1,
        magical_damage: 1.03,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 3,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 5,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 1,
        kyosir: 0,
        imgURL: '/images/sage-ring.png'
    },
    {
        name: "Quor'ite Ring",
        type: 'Magic',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_penetration: 2,
        magical_penetration: 2,
        physical_resistance: 2,
        magical_resistance: 2,
        critical_chance: 1,
        critical_damage: 1.02,
        dodge: 0,
        roll: 3,
        constitution: 2,
        strength: 0,
        agility: 1,
        achre: 1,
        caeren: 0,
        kyosir: 1,
        imgURL: '/images/earth-ring.png'
    },
    {
        name: 'Fang Ring',
        type: 'Physical',
        physical_damage: 1.03,
        magical_damage: 1.03,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.1,
        dodge: 0,
        roll: 1,
        constitution: 0,
        strength: 3,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        imgURL: '/images/fang-ring.png'
    },
    {
        name: 'Fireland Ring',
        type: 'Physical',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 2,
        achre: 2,
        caeren: 0,
        kyosir: 1,
        imgURL: '/images/fireland-ring.png'
    },
    {
        name: "Marauder's Ring",
        type: 'Physical',
        physical_damage: 1.04,
        magical_damage: 1,
        physical_penetration: 5,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 0,
        roll: 2,
        constitution: 0,
        strength: 2,
        agility: 2,
        achre: 0,
        caeren: 1,
        kyosir: 0,
        imgURL: '/images/marauder-ring.png'
    },
    {
        name: 'Occult Ring',
        type: 'Magic',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_penetration: 3,
        magical_penetration: 3,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 2,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 2,
        kyosir: 1,
        imgURL: '/images/occult-ring.png'
    },  
    {
        name: 'Fyers Ring',
        type: 'Magic',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_penetration: 0,
        magical_penetration: 5,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 4,
        kyosir: 1,
        imgURL: '/images/fyers-ring.png'
    },
    {
        name: 'Astral Ring',
        type: 'Magic',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_penetration: 0,
        magical_penetration: 5,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.1,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 4,
        caeren: 0,
        kyosir: 1,
        imgURL: '/images/astral-ring.png'
    },
    {
        name: 'Dae Ring',
        type: 'Magic',
        physical_damage: 1,
        magical_damage: 1.02,
        physical_penetration: 2,
        magical_penetration: 2,
        physical_resistance: 2,
        magical_resistance: 2,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 0,
        roll: 2,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 1,
        caeren: 1,
        kyosir: 1,
        imgURL: '/images/dae-ring.png'
    },
];

const seedAmulets = [
    {
        name: "Knight's Amulet",
        type: 'Magic',
        physical_damage: 1.03,
        magical_damage: 1,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 0,
        roll: 3,
        constitution: 3,
        strength: 2,
        agility: 0,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/knight-amulet.png'
    },
    {
        name: "Ashtre Amulet",
        type: 'Magic',
        physical_damage: 1.05,
        magical_damage: 0.97,
        physical_penetration: 5,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 2,
        agility: 2,
        achre: 1,
        caeren: 0,
        kyosir: 0,
        influences: ["Astra"],
        imgURL: '/images/ashtre-amulet.png'
    },
    {
        name: 'Soverain Amulet',
        type: 'Magic',
        physical_damage: 1,
        magical_damage: 1.03,
        physical_penetration: 5,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 3,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 3,
        kyosir: 0,
        influences: ["Ilios"],
        imgURL: '/images/soverain-amulet.png'
    },
    {
        name: 'Daethic Amulet',
        type: 'Magic',
        physical_damage: 1.03,
        magical_damage: 1,
        physical_penetration: 2,
        magical_penetration: 2,
        physical_resistance: 2,
        magical_resistance: 2,
        critical_chance: 2,
        critical_damage: 1.05,
        dodge: 0,
        roll: 2,
        constitution: 1,
        strength: 1,
        agility: 1,
        achre: 1,
        caeren: 1,
        kyosir: 0,
        influences: ["Daethos"],
        imgURL: '/images/daethic-amulet.png'
    },
    {
        name: 'Achreon Amulet',
        type: 'Magic',
        physical_damage: 1.05,
        magical_damage: 0.97,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 5,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 5,
        caeren: 0,
        kyosir: 0,
        influences: ["Achreo"],
        imgURL: '/images/achre-amulet.png'
    },
    {
        name: 'Cambiren Amulet',
        type: 'Magic',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 3,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 5,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 5,
        kyosir: 0,
        influences: ["Cambire"],
        imgURL: '/images/caeren-amulet.png'
    },
    {
        name: 'Sage Amulet',
        type: 'Magic',
        physical_damage: 1,
        magical_damage: 1.03,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 3,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 5,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 1,
        kyosir: 0,
        influences: ["Senari"],
        imgURL: '/images/sage-amulet.png'
    },
    {
        name: "Quor'ite Amulet",
        type: 'Magic',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_penetration: 2,
        magical_penetration: 2,
        physical_resistance: 2,
        magical_resistance: 2,
        critical_chance: 1,
        critical_damage: 1.02,
        dodge: 0,
        roll: 3,
        constitution: 2,
        strength: 0,
        agility: 1,
        achre: 1,
        caeren: 0,
        kyosir: 1,
        influences: ["Quor'ei"],
        imgURL: '/images/earth-amulet.png'
    },
    {
        name: 'Fang Amulet',
        type: 'Physical',
        physical_damage: 1.03,
        magical_damage: 1.03,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.1,
        dodge: 0,
        roll: 1,
        constitution: 0,
        strength: 3,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/fang-amulet.png'
    },
    {
        name: 'Fireland Amulet',
        type: 'Physical',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 2,
        achre: 2,
        caeren: 0,
        kyosir: 1,
        influences: ["Fyero"],
        imgURL: '/images/fireland-amulet.png'
    },
    {
        name: "Marauder's Amulet",
        type: 'Physical',
        physical_damage: 1.04,
        magical_damage: 1,
        physical_penetration: 5,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 0,
        roll: 2,
        constitution: 0,
        strength: 2,
        agility: 2,
        achre: 0,
        caeren: 1,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/marauder-amulet.png'
    },
    {
        name: 'Occult Amulet',
        type: 'Magic',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_penetration: 3,
        magical_penetration: 3,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 2,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 2,
        kyosir: 1,
        influences: ["Ma'anre"],
        imgURL: '/images/occult-amulet.png'
    },  
    {
        name: 'Fyers Amulet',
        type: 'Magic',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_penetration: 0,
        magical_penetration: 5,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 4,
        kyosir: 1,
        influences: ["Fyero"],
        imgURL: '/images/fyers-amulet.png'
    },
    {
        name: 'Astral Amulet',
        type: 'Magic',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_penetration: 0,
        magical_penetration: 5,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.1,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 4,
        caeren: 0,
        kyosir: 1,
        influences: ["Astra"],
        imgURL: '/images/astral-amulet.png'
    },
    {
        name: 'Dae Amulet',
        type: 'Magic',
        physical_damage: 1,
        magical_damage: 1.02,
        physical_penetration: 2,
        magical_penetration: 2,
        physical_resistance: 2,
        magical_resistance: 2,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 0,
        roll: 2,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 1,
        caeren: 1,
        kyosir: 1,
        influences: ["Daethos"],
        imgURL: '/images/dae-amulet.png'
    },
];

const seedTrinkets = [
    {
        name: "Knight's Trinket",
        type: 'Magic',
        physical_damage: 1.03,
        magical_damage: 1,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 0,
        roll: 3,
        constitution: 3,
        strength: 2,
        agility: 0,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/knight-trinket.png'
    },
    {
        name: "Ashtre Trinket",
        type: 'Magic',
        physical_damage: 1.05,
        magical_damage: 0.97,
        physical_penetration: 5,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 2,
        agility: 2,
        achre: 1,
        caeren: 0,
        kyosir: 0,
        influences: ["Astra"],
        imgURL: '/images/ashtre-trinket.png'
    },
    {
        name: 'Soverain Trinket',
        type: 'Magic',
        physical_damage: 1,
        magical_damage: 1.03,
        physical_penetration: 5,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 3,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 3,
        kyosir: 0,
        influences: ["Ilios"],
        imgURL: '/images/soverain-trinket.png'
    },
    {
        name: 'Daethic Trinket',
        type: 'Magic',
        physical_damage: 1.05,
        magical_damage: 1,
        physical_penetration: 2,
        magical_penetration: 2,
        physical_resistance: 2,
        magical_resistance: 2,
        critical_chance: 2,
        critical_damage: 1.05,
        dodge: 0,
        roll: 2,
        constitution: 1,
        strength: 1,
        agility: 1,
        achre: 1,
        caeren: 1,
        kyosir: 0,
        influences: ["Daethos"],
        imgURL: '/images/daethic-trinket.png'
    },
    {
        name: 'Achreon Trinket',
        type: 'Magic',
        physical_damage: 1.05,
        magical_damage: 0.97,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 5,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 5,
        caeren: 0,
        kyosir: 0,
        influences: ["Achreo"],
        imgURL: '/images/achre-trinket.png'
    },
    {
        name: 'Cambiren Trinket',
        type: 'Magic',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 3,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 5,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 5,
        kyosir: 0,
        influences: ["Cambire"],
        imgURL: '/images/caeren-trinket.png'
    },
    {
        name: 'Sage Trinket',
        type: 'Magic',
        physical_damage: 1,
        magical_damage: 1.03,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 3,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 5,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 1,
        kyosir: 0,
        influences: ["Senari"],
        imgURL: '/images/sage-trinket.png'
    },
    {
        name: "Quor'ite Trinket",
        type: 'Magic',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_penetration: 2,
        magical_penetration: 2,
        physical_resistance: 2,
        magical_resistance: 2,
        critical_chance: 1,
        critical_damage: 1.02,
        dodge: 0,
        roll: 3,
        constitution: 2,
        strength: 0,
        agility: 1,
        achre: 1,
        caeren: 0,
        kyosir: 1,
        influences: ["Quor'ei"],
        imgURL: '/images/earth-trinket.png'
    },
    {
        name: 'Fang Trinket',
        type: 'Physical',
        physical_damage: 1.03,
        magical_damage: 1.03,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.1,
        dodge: 0,
        roll: 1,
        constitution: 0,
        strength: 3,
        agility: 2,
        achre: 0,
        caeren: 0,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/fang-trinket.png'
    },
    {
        name: 'Fireland Trinket',
        type: 'Physical',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_penetration: 3,
        magical_penetration: 0,
        physical_resistance: 3,
        magical_resistance: 0,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 2,
        achre: 2,
        caeren: 0,
        kyosir: 1,
        influences: ["Fyero"],
        imgURL: '/images/fireland-trinket.png'
    },
    {
        name: "Marauder's Trinket",
        type: 'Physical',
        physical_damage: 1.04,
        magical_damage: 1,
        physical_penetration: 5,
        magical_penetration: 0,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.03,
        dodge: 0,
        roll: 2,
        constitution: 0,
        strength: 2,
        agility: 2,
        achre: 0,
        caeren: 1,
        kyosir: 0,
        influences: ["Se'vas"],
        imgURL: '/images/marauder-trinket.png'
    },
    {
        name: 'Occult Trinket',
        type: 'Magic',
        physical_damage: 1.02,
        magical_damage: 1.02,
        physical_penetration: 3,
        magical_penetration: 3,
        physical_resistance: 0,
        magical_resistance:20,
        critical_chance: 2,
        critical_damage: 1.03,
        dodge: 0,
        roll: 2,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 2,
        caeren: 2,
        kyosir: 1,
        influences: ["Ma'anre"],
        imgURL: '/images/occult-trinket.png'
    },  
    {
        name: 'Fyers Trinket',
        type: 'Magic',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_penetration: 0,
        magical_penetration: 5,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 0,
        caeren: 4,
        kyosir: 1,
        influences: ["Fyero"],
        imgURL: '/images/fyers-trinket.png'
    },
    {
        name: 'Astral Trinket',
        type: 'Magic',
        physical_damage: 0.97,
        magical_damage: 1.05,
        physical_penetration: 0,
        magical_penetration: 5,
        physical_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.05,
        dodge: 0,
        roll: 3,
        constitution: 0,
        strength: 0,
        agility: 0,
        achre: 4,
        caeren: 0,
        kyosir: 1,
        influences: ["Astra"],
        imgURL: '/images/astral-trinket.png'
    },
    {
        name: 'Dae Trinket',
        type: 'Magic',
        physical_damage: 1,
        magical_damage: 1.02,
        physical_penetration: 2,
        magical_penetration: 2,
        physical_resistance: 2,
        magical_resistance: 2,
        critical_chance: 2,
        critical_damage: 1.02,
        dodge: 0,
        roll: 2,
        constitution: 2,
        strength: 0,
        agility: 0,
        achre: 1,
        caeren: 1,
        kyosir: 1,
        influences: ["Daethos"],
        imgURL: '/images/dae-trinket.png'
    },
];

const seedDB = async () => {
    // const filter = { seedWeapons }
    await Weapons.deleteMany({});
    await Weapons.insertMany(seedWeapons);
    // await Weapons.updateMany(filter, seedWeapons);
    console.log(seedWeapons, "Here are the seeded weapons");

    await Shields.deleteMany({});
    await Shields.insertMany(seedShields);
    // await Shields.updateMany(seedShields);

    await Helmets.deleteMany({});
    await Helmets.insertMany(seedHelmets);
    // await Helmets.updateMany(seedHelmets);

    await Chests.deleteMany({});
    await Chests.insertMany(seedChests);
    // await Chests.updateMany(seedChests);

    await Legs.deleteMany({});
    await Legs.insertMany(seedLegs);
    // await Legs.updateMany(seedLegs);

    await Rings.deleteMany({});
    await Rings.insertMany(seedRings);
    // await Rings.updateMany(seedRings);

    await Amulets.deleteMany({});
    await Amulets.insertMany(seedAmulets);
    // await Amulets.updateMany(seedAmulets);

    await Trinkets.deleteMany({});
    await Trinkets.insertMany(seedTrinkets);
    // await Trinkets.updateMany(seedTrinkets);
    console.log(seedTrinkets, "Here are the seeded trinkets");
};
seedDB().then(() => {
    mongoose.connection.close();
});
