const mongoose = require('mongoose');
const Weapons = require('./models/weapon');
const Shields = require('./models/shield');
const Helmets = require('./models/helmet');
const Chests = require('./models/chest');

mongoose.connect(`mongodb+srv://Daethos:8_pCXPeG$kyvN2n@cluster0.ivsipz0.mongodb.net/seyr?retryWrites=true&w=majority`, 
    {
    useNewUrlParser: true, useUnifiedTopology: true })
        .then(() => {
            console.log('Mongo Connection Open!');
        })
        .catch((err) => {
            console.log(err)
        });

const seedWeapons = [
    {
        name: 'Gladius',
        type: 'Short Sword',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 8,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 1.5,
        dodge: 3,
        roll: 3,
        imgURL: '/images/gladius.png'
    },
    {
        name: 'Pugio',
        type: 'Dagger',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 5,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 10,
        critical_damage: 2.25,
        dodge: 0,
        roll: 7,
        imgURL: '/images/pugio.png'
    },
    {
        name: 'Shotel',
        type: 'Scythe',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 5,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 5,
        critical_damage: 2.75,
        dodge: 0,
        roll: 5,
        imgURL: '/images/scythe.png'
    },
    {
        name: 'Spear',
        type: 'Polearm',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce'],
        physical_damage: 7,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 7,
        critical_damage: 1.75,
        dodge: 3,
        roll: 5,
        imgURL: '/images/spear.png'
    },
    {
        name: 'Halberd',
        type: 'Polearm',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 13,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 5,
        critical_damage: 2.5,
        dodge: 5,
        roll: 3,
        imgURL: '/images/halberd.png'
    },
    {
        name: 'Claymore',
        type: 'Greatsword',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Slash'],
        physical_damage: 13,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 5,
        critical_damage: 2.5,
        dodge: 5,
        roll: 3,
        imgURL: '/images/claymore.png'
    },
    {
        name: 'Battle Axe',
        type: 'Greataxe',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Slash'],
        physical_damage: 13,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 5,
        critical_damage: 2.5,
        dodge: 5,
        roll: 3,
        imgURL: '/images/battleaxe.png'
    },
    {
        name: 'War Hammer',
        type: 'Greatmace',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Blunt'],
        physical_damage: 13,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 5,
        critical_damage: 2.5,
        dodge: 5,
        roll: 3,
        imgURL: '/images/warhammer.png'
    },
    {
        name: 'Morningstar',
        type: 'Mace',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Blunt', 'Pierce'],
        physical_damage: 7,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 7,
        critical_damage: 2,
        dodge: 3,
        roll: 5,
        imgURL: '/images/morningstar.png'
    },
    {
        name: 'Pernach',
        type: 'Mace',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Blunt'],
        physical_damage: 9,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 5,
        critical_damage: 1.5,
        dodge: 3,
        roll: 3,
        imgURL: '/images/mace.png'
    },
    {
        name: "Hand of Se'dyro",
        type: 'Mace',
        grip: 'One Hand',
        attack_type: 'Physical',
        damage_type: ['Blunt'],
        physical_damage: 7,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 7,
        critical_damage: 2,
        dodge: 3,
        roll: 7,
        imgURL: '/images/godHand.png'
    },
    {
        name: 'Whirlwind',
        type: 'Scythe',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce', 'Slash'],
        physical_damage: 6,
        magical_damage: 6,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 7,
        critical_damage: 2.5,
        dodge: 5,
        roll: 7,
        imgURL: '/images/whirlwind.png'
    },
    {
        name: 'Lava Spit',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Fire'],
        physical_damage: 0,
        magical_damage: 10,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 10,
        critical_damage: 2.5,
        dodge: 5,
        roll: 10,
        imgURL: '/images/fire.png'
    },
    {
        name: 'Astral Spear',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Lightning'],
        physical_damage: 0,
        magical_damage: 10,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 10,
        critical_damage: 2.5,
        dodge: 5,
        roll: 10,
        imgURL: '/images/astral-spear.png'
    },
    {
        name: 'Caeren Barrage',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Sorcery'],
        physical_damage: 0,
        magical_damage: 7,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 7,
        critical_damage: 1.5,
        dodge: 5,
        roll: 7,
        imgURL: '/images/sorcery.png'
    },
    {
        name: 'Arctic Bolt',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Frost'],
        physical_damage: 0,
        magical_damage: 9,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 5,
        critical_damage: 1.5,
        dodge: 0,
        roll: 5,
        imgURL: '/images/frost.png'
    },
    {
        name: "Quor'ite Crush",
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Earth'],
        physical_damage: 0,
        magical_damage: 9,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 5,
        critical_damage: 1.5,
        dodge: 0,
        roll: 5,
        imgURL: '/images/earth.png'
    },
    {
        name: 'Hush',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Faith'],
        physical_damage: 4,
        magical_damage: 4,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 7,
        critical_damage: 1.5,
        dodge: 3,
        roll: 7,
        imgURL: '/images/faith.png'
    },
    {
        name: 'Tendrils',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Spooky'],
        physical_damage: 5,
        magical_damage: 5,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 7,
        critical_damage: 2,
        dodge: 3,
        roll: 7,
        imgURL: '/images/tendrils.png'
    },
    {
        name: 'Windfury',
        type: 'Spell',
        grip: 'One Hand',
        attack_type: 'Magic',
        damage_type: ['Wind'],
        physical_damage: 0,
        magical_damage: 7,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 7,
        critical_damage: 1.5,
        dodge: 3,
        roll: 7,
        imgURL: '/images/windfury.png'
    },
    {
        name: 'Longbow',
        type: 'Bow',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce'],
        physical_damage: 9,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 7,
        critical_damage: 2,
        dodge: 7,
        roll: 3,
        imgURL: '/images/bow-long.png'
    },
    {
        name: 'Reflex',
        type: 'Bow',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce'],
        physical_damage: 11,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 3,
        critical_damage: 3,
        dodge: 7,
        roll: 3,
        imgURL: '/images/bow-reflex.png'
    },
    {
        name: 'Recurve',
        type: 'Bow',
        grip: 'Two Hand',
        attack_type: 'Physical',
        damage_type: ['Pierce'],
        physical_damage: 10,
        magical_damage: 0,
        phyiscal_resistance: 0,
        magical_resistance: 0,
        critical_chance: 5,
        critical_damage: 2.5,
        dodge: 5,
        roll: 5,
        imgURL: '/images/bow-recurve.png'
    }
];

const seedHelmets = [
    {
        name: 'Ashtre Helm',
        type: 'Plate-Mail',
        physical_damage: 1.1,
        magical_damage: 1.1,
        phyiscal_resistance: 25,
        magical_resistance: 25,
        critical_chance: 5,
        critical_damage: 1.1,
        dodge: 3,
        roll: 5,
        imgURL: '/images/ashtre-helm.png'
    },
    {
        name: 'Chain-Knight Helm',
        type: 'Chain-Mail',
        physical_damage: 1.25,
        magical_damage: 1,
        phyiscal_resistance: 20,
        magical_resistance: 15,
        critical_chance: 5,
        critical_damage: 1.25,
        dodge: 3,
        roll: 5,
        imgURL: '/images/chain-helm.png'
    },
    {
        name: 'Fang Helm',
        type: 'Chain-Mail',
        physical_damage: 1.15,
        magical_damage: 1.15,
        phyiscal_resistance: 20,
        magical_resistance: 20,
        critical_chance: 5,
        critical_damage: 1.15,
        dodge: 3,
        roll: 5,
        imgURL: '/images/fang-helm.png'
    },
    {
        name: 'Fireland Helm',
        type: 'Plate-Mail',
        physical_damage: 1.25,
        magical_damage: 1.15,
        phyiscal_resistance: 25,
        magical_resistance: 15,
        critical_chance: 5,
        critical_damage: 1.25,
        dodge: 3,
        roll: 5,
        imgURL: '/images/fireland-helm.png'
    },
    {
        name: "Marauder's Helm",
        type: 'Leather-Mail',
        physical_damage: 1.25,
        magical_damage: 1.05,
        phyiscal_resistance: 15,
        magical_resistance: 10,
        critical_chance: 5,
        critical_damage: 1.15,
        dodge: 3,
        roll: 5,
        imgURL: '/images/marauder-helm.png'
    },
    {
        name: 'Soverain Helm',
        type: 'Plate-Mail',
        physical_damage: 1.15,
        magical_damage: 1.25,
        phyiscal_resistance: 15,
        magical_resistance: 25,
        critical_chance: 5,
        critical_damage: 1.25,
        dodge: 3,
        roll: 5,
        imgURL: '/images/soverain-helm.png'
    },
    {
        name: 'Occult Mask',
        type: 'Leather-Mail',
        physical_damage: 1.1,
        magical_damage: 1.1,
        phyiscal_resistance: 15,
        magical_resistance: 25,
        critical_chance: 5,
        critical_damage: 1.25,
        dodge: 1,
        roll: 7,
        imgURL: '/images/occult-helm.png'
    },
    {
        name: 'Fyers Hood',
        type: 'Cloth-Leather',
        physical_damage: 0.85,
        magical_damage: 1.25,
        phyiscal_resistance: 5,
        magical_resistance: 20,
        critical_chance: 7,
        critical_damage: 1.5,
        dodge: 1,
        roll: 7,
        imgURL: '/images/fyers-hood.png'
    },
    {
        name: "Quor'ite Hood",
        type: 'Cloth-Leather',
        physical_damage: 1,
        magical_damage: 1.15,
        phyiscal_resistance: 15,
        magical_resistance: 15,
        critical_chance: 5,
        critical_damage: 1.15,
        dodge: 0,
        roll: 5,
        imgURL: '/images/earth-hood.png'
    },
    {
        name: 'Astral Hood',
        type: 'Cloth-Leather',
        physical_damage: 0.85,
        magical_damage: 1.25,
        phyiscal_resistance: 5,
        magical_resistance: 20,
        critical_chance: 7,
        critical_damage: 1.5,
        dodge: 1,
        roll: 7,
        imgURL: '/images/astral-hood.png'
    },
    {
        name: 'Dae Hood',
        type: 'Cloth-Leather',
        physical_damage: 1.15,
        magical_damage: 1.15,
        phyiscal_resistance: 15,
        magical_resistance: 15,
        critical_chance: 5,
        critical_damage: 1.25,
        dodge: 1,
        roll: 5,
        imgURL: '/images/dae-hood.png'
    },
    {
        name: 'Sage Hood',
        type: 'Cloth-Leather',
        physical_damage: 0.9,
        magical_damage: 1.15,
        phyiscal_resistance: 5,
        magical_resistance: 25,
        critical_chance: 0,
        critical_damage: 1.25,
        dodge: 0,
        roll: 15,
        imgURL: '/images/sage-hood.png'
    },
    {
        name: "Knight's Helm",
        type: 'Plate-Mail',
        physical_damage: 1.15,
        magical_damage: 1,
        phyiscal_resistance: 25,
        magical_resistance: 15,
        critical_chance: 7,
        critical_damage: 1.15,
        dodge: 3,
        roll: 5,
        imgURL: '/images/knight-helm.png'
    },
    {
        name: 'Daethic Helm',
        type: 'Plate-Mail',
        physical_damage: 1,
        magical_damage: 1.15,
        phyiscal_resistance: 15,
        magical_resistance: 25,
        critical_chance: 5,
        critical_damage: 1.15,
        dodge: 3,
        roll: 5,
        imgURL: '/images/daethic-helm.png'
    },
    {
        name: 'Achreon Helm',
        type: 'Leather-Mail',
        physical_damage: 1.15,
        magical_damage: 1.15,
        phyiscal_resistance: 15,
        magical_resistance: 15,
        critical_chance: 5,
        critical_damage: 1.25,
        dodge: 5,
        roll: 10,
        imgURL: '/images/achreon-helm.png'
    },
    {
        name: 'Licivitan Helm',
        type: 'Leather-Mail',
        physical_damage: 1.15,
        magical_damage: 1.15,
        phyiscal_resistance: 15,
        magical_resistance: 15,
        critical_chance: 5,
        critical_damage: 1.5,
        dodge: 5,
        roll: 15,
        imgURL: '/images/legion-helm.png'
    },
];

const seedChests = [
    {
        name: "Knight's Cuirass",
        type: 'Plate-Mail',
        physical_damage: 1.1,
        magical_damage: 1,
        phyiscal_resistance: 20,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.1,
        dodge: 5,
        roll: 3,
        imgURL: '/images/knight-armor.png'
    },
    {
        name: 'Daethic Cuirass',
        type: 'Plate-Mail',
        physical_damage: 1,
        magical_damage: 1.1,
        phyiscal_resistance: 10,
        magical_resistance: 20,
        critical_chance: 3,
        critical_damage: 1.1,
        dodge: 5,
        roll: 3,
        imgURL: '/images/daethic-armor.png'
    },
    {
        name: 'Achreon Armor',
        type: 'Leather-Mail',
        physical_damage: 1.15,
        magical_damage: 1.15,
        phyiscal_resistance: 10,
        magical_resistance: 10,
        critical_chance: 5,
        critical_damage: 1.25,
        dodge: 5,
        roll: 5,
        imgURL: '/images/achreon-armor.png'
    },
    {
        name: 'Sage Robes',
        type: 'Leather-Cloth',
        physical_damage: 0.9,
        magical_damage: 1.15,
        phyiscal_resistance: 5,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.1,
        dodge: 3,
        roll: 1,
        imgURL: '/images/sage-robes.png'
    },
    {
        name: 'Licivitan Cuirass',
        type: 'Leather-Mail',
        physical_damage: 1.05,
        magical_damage: 1.05,
        phyiscal_resistance: 10,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.1,
        dodge: 5,
        roll: 10,
        imgURL: '/images/daethic-armor.png'
    },
];

const seedShields = [
    {
        name: 'Parrying Buckler',
        type: 'Small Shield',
        physical_damage: 1.05,
        magical_damage: 1.05,
        phyiscal_resistance: 5,
        magical_resistance: 5,
        critical_chance: 5,
        critical_damage: 1.1,
        dodge: 1,
        roll: 7,
        imgURL: '/images/daethic-armor.png'
    },
    {
        name: 'Heater',
        type: 'Medium Shield',
        physical_damage: 1.05,
        magical_damage: 1.05,
        phyiscal_resistance: 10,
        magical_resistance: 10,
        critical_chance: 3,
        critical_damage: 1.1,
        dodge: 3,
        roll: 3,
        imgURL: '/images/heater-shield.png'
    },
    {
        name: 'Scutum',
        type: 'Leather-Mail',
        physical_damage: 1,
        magical_damage: 1,
        phyiscal_resistance: 20,
        magical_resistance: 20,
        critical_chance: 3,
        critical_damage: 1.1,
        dodge: 5,
        roll: 1,
        imgURL: '/images/scutum.png'
    },
    {
        name: 'Pavise',
        type: 'Great Shield',
        physical_damage: 1,
        magical_damage: 1,
        phyiscal_resistance: 30,
        magical_resistance: 30,
        critical_chance: 0,
        critical_damage: 1,
        dodge: 0,
        roll: 0,
        imgURL: '/images/pavise.png'
    }
];


const seedDB = async () => {
    await Weapons.deleteMany({});
    await Weapons.insertMany(seedWeapons);
    console.log(seedWeapons, "Here are the seeded weapons");

    await Shields.deleteMany({});
    await Shields.insertMany(seedShields);

    await Helmets.deleteMany({});
    await Helmets.insertMany(seedHelmets);

    await Chests.deleteMany({});
    await Chests.insertMany(seedChests);

};
seedDB().then(() => {
    mongoose.connection.close();
});
