import { Enemy, Equipment } from './GameStore';

function findSex() {
    const chance = Math.floor(Math.random() * 2);
    if (chance === 0) {
        return "Male";
    } else {
        return "Female";
    };
};

const Wolf_Claw: Equipment = {
    name: "Wolf's Paw",
    type: 'Natural',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: 'One Hand',
    attack_type: 'Physical',
    damage_type: ['Slash'],
    physical_damage: 2,
    magical_damage: 0,
    physical_penetration: 1,
    magical_penetration: 0,
    physical_resistance: 0,
    magical_resistance: 0,
    critical_chance: 1,
    critical_damage: 1.01,
    dodge: 0,
    roll: 3,
    constitution: 0,
    strength: 0,
    agility: 2,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Kyn'gi"],
    imgURL: '/images/wolf-claw.png',
    _id: '001'
};

const Wolf_Bite: Equipment = {
    name: "Wolf's Bite",
    type: 'Natural',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: 'One Hand',
    attack_type: 'Physical',
    damage_type: ['Blunt'],
    physical_damage: 3,
    magical_damage: 0,
    physical_penetration: 1,
    magical_penetration: 0,
    physical_resistance: 0,
    magical_resistance: 0,
    critical_chance: 1,
    critical_damage: 1.01,
    dodge: 5,
    roll: 0,
    constitution: 0,
    strength: 0,
    agility: 2,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Kyn'gi"],
    imgURL: '/images/wolf-crunch.png',
    _id: '002'
};

const Wolf_Tear: Equipment = {
    name: "Wolf's Crunchy Chew",
    type: 'Natural',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: 'One Hand',
    attack_type: 'Physical',
    damage_type: ['Pierce'],
    physical_damage: 2,
    magical_damage: 0,
    physical_penetration: 1,
    magical_penetration: 0,
    physical_resistance: 0,
    magical_resistance: 0,
    critical_chance: 1,
    critical_damage: 1.01,
    dodge: 2,
    roll: 2,
    constitution: 0,
    strength: 0,
    agility: 2,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Kyn'gi"],
    imgURL: '/images/wolf-bite.png',
    _id: '003'
};

const Wolf_Tail: Equipment = {
    name: "Wolf's Tail",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2.5,
    magical_resistance: 2.5,
    critical_chance: 3,
    critical_damage: 1.03,
    dodge: 0,
    roll: 2,
    constitution: 0,
    strength: 0,
    agility: 2,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/wolf-tail.png',
    _id: '004'
};

const Wolf_Head: Equipment = {
    name: "Wolf's Head",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2.5,
    magical_resistance: 1.5,
    critical_chance: 3,
    critical_damage: 1.03,
    dodge: 0,
    roll: 2,
    constitution: 1,
    strength: 0,
    agility: 1,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/wolf-head.png',
    _id: '005'
};

const Wolf_Upper_Torso: Equipment = {
    name: "Wolf's Upper Torso",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2.5,
    magical_resistance: 1.5,
    critical_chance: 3,
    critical_damage: 1.03,
    dodge: 0,
    roll: 3,
    constitution: 1,
    strength: 0,
    agility: 1,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/wolf-upper.png',
    _id: '006'
};

const Wolf_Lower_Body: Equipment = {
    name: "Wolf's Lower Body",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2.5,
    magical_resistance: 1.5,
    critical_chance: 3,
    critical_damage: 1.03,
    dodge: 0,
    roll: 3,
    constitution: 1,
    strength: 0,
    agility: 1,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/wolf-lower.png',
    _id: '007'
};

const Wolf_Leg: Equipment = {
    name: "Wolf's Leg",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2,
    magical_resistance: 1,
    critical_chance: 3,
    critical_damage: 1.03,
    dodge: 0,
    roll: 2,
    constitution: 0,
    strength: 0,
    agility: 1,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Kyn'gi"],
    imgURL: '/images/wolf-leg.png',
    _id: '008'
};


export const Wolf: Enemy = {
    name: "Wolf",
    description: "A stray wolf wandering.",
    user: {},
    constitution: 10,
    strength: 10,
    agility: 12,
    achre: 10,
    caeren: 10,
    kyosir: 10,
    named: false,
    type: 'Wolf, Untouched',
    humanoid: false,
    animal: true,
    weapon_one: Wolf_Claw,
    weapon_two: Wolf_Bite,
    weapon_three: Wolf_Tear,
    shield: Wolf_Tail,
    helmet: Wolf_Head,
    chest: Wolf_Upper_Torso,
    legs: Wolf_Lower_Body,
    amulet: Wolf_Leg,
    ring_one: Wolf_Leg,
    ring_two: Wolf_Leg,
    trinket: Wolf_Leg,
    faith: 'adherent',
    mastery: 'Agility',
    origin: 'Wolf',
    sex: findSex(),
    currency: {},
    experience: 0,
    high_score: 0,
    level: 0.5,
    coordinates: {},
    firewater: {},
    inventory: [],
    maps: [],
    quests: [],
    tutorial: {},
    index: '',
    shareable: '',
    visibiility: '',
    dislikes: [],
    double_dislikes: [],
    likes: []
};

const Bear_Claw: Equipment = {
    name: "Bear Claw",
    type: 'Natural',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: 'Two Hand',
    attack_type: 'Physical',
    damage_type: ['Slash', 'Pierce'],
    physical_damage: 3,
    magical_damage: 0,
    physical_penetration: 3,
    magical_penetration: 0,
    physical_resistance: 0,
    magical_resistance: 0,
    critical_chance: 3,
    critical_damage: 1.25,
    dodge: 0,
    roll: 3,
    constitution: 0,
    strength: 2,
    agility: 2,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Se'vas"],
    imgURL: '/images/bear-claw.png',
    _id: '101'
};
const Bear_Swipe: Equipment = {
    name: "Bear Swipes",
    type: 'Natural',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: 'Two Hand',
    attack_type: 'Physical',
    damage_type: ['Slash'],
    physical_damage: 4,
    magical_damage: 0,
    physical_penetration: 2,
    magical_penetration: 0,
    physical_resistance: 0,
    magical_resistance: 0,
    critical_chance: 2,
    critical_damage: 1.25,
    dodge: 0,
    roll: 2,
    constitution: 0,
    strength: 4,
    agility: 0,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Se'vas"],
    imgURL: '/images/bear-swipe.png',
    _id: '102'
};
const Bear_Maul: Equipment = {
    name: "Bear Maul",
    type: 'Natural',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: 'Two Hand',
    attack_type: 'Physical',
    damage_type: ['Blunt', 'Pierce'],
    physical_damage: 3,
    magical_damage: 0,
    physical_penetration: 3,
    magical_penetration: 0,
    physical_resistance: 0,
    magical_resistance: 0,
    critical_chance: 3,
    critical_damage: 1.25,
    dodge: 0,
    roll: 3,
    constitution: 0,
    strength: 4,
    agility: 0,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Se'vas"],
    imgURL: '/images/bear-maul.png',
    _id: '103'
};

const Bear_Bones: Equipment = {
    name: "Bear Bones",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 12.5,
    magical_resistance: 12.5,
    critical_chance: 1,
    critical_damage: 1.01,
    dodge: 5,
    roll: 0,
    constitution: 2,
    strength: 2,
    agility: 0,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/bear-armor.png',
    _id: '104'
};

const Bear_Head: Equipment = {
    name: "Bear's Head",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 12.5,
    magical_resistance: 3.5,
    critical_chance: 2,
    critical_damage: 1.05,
    dodge: 3,
    roll: 1,
    constitution: 2,
    strength: 2,
    agility: 0,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/bear-head.png',
    _id: '105'
};

const Bear_Upper_Torso: Equipment = {
    name: "Bear's Upper Torso",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 12.5,
    magical_resistance: 3.5,
    critical_chance: 2,
    critical_damage: 1.05,
    dodge: 3,
    roll: 1,
    constitution: 2,
    strength: 2,
    agility: 0,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/bear-upper.png',
    _id: '106'
};

const Bear_Lower_Body: Equipment = {
    name: "Bear's Lower Body",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 12.5,
    magical_resistance: 3.5,
    critical_chance: 2,
    critical_damage: 1.05,
    dodge: 3,
    roll: 1,
    constitution: 2,
    strength: 2,
    agility: 0,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/bear-lower.png',
    _id: '107'
};

const Bear_Right_Arm: Equipment = {
    name: "Bear's Right Arm",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 2,
    magical_penetration: 1,
    physical_resistance: 0,
    magical_resistance: 0,
    critical_chance: 2,
    critical_damage: 1.05,
    dodge: 0,
    roll: 1,
    constitution: 0,
    strength: 1,
    agility: 0,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Se'vas"],
    imgURL: '/images/bear-right.png',
    _id: '108'
};

const Bear_Left_Arm: Equipment = {
    name: "Bear's Left Arm",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 2,
    magical_penetration: 1,
    physical_resistance: 0,
    magical_resistance: 0,
    critical_chance: 2,
    critical_damage: 1.05,
    dodge: 0,
    roll: 1,
    constitution: 0,
    strength: 1,
    agility: 0,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Se'vas"],
    imgURL: '/images/bear-left.png',
    _id: '109'
};

const Bear_Right_Leg: Equipment = {
    name: "Bear's Right Leg",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2,
    magical_resistance: 1,
    critical_chance: 2,
    critical_damage: 1.05,
    dodge: 0,
    roll: 1,
    constitution: 1,
    strength: 0,
    agility: 0,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Se'vas"],
    imgURL: '/images/bear-foot-right.png',
    _id: '110'
};

const Bear_Left_Leg: Equipment = {
    name: "Bear's Left Leg",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2,
    magical_resistance: 1,
    critical_chance: 2,
    critical_damage: 1.05,
    dodge: 0,
    roll: 1,
    constitution: 1,
    strength: 0,
    agility: 0,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Se'vas"],
    imgURL: '/images/bear-foot-left.png',
    _id: '111'
};

export const Bear: Enemy = {
    name: "Bear",
    description: "A starved bear caught attempting to survive.",
    user: {},
    constitution: 10,
    strength: 18,
    agility: 14,
    achre: 12,
    caeren: 10,
    kyosir: 10,
    named: false,
    type: 'Bear, Untouched',
    humanoid: false,
    animal: true,
    weapon_one: Bear_Claw,
    weapon_two: Bear_Swipe,
    weapon_three: Bear_Maul,
    shield: Bear_Bones,
    helmet: Bear_Head,
    chest: Bear_Upper_Torso,
    legs: Bear_Lower_Body,
    amulet: Bear_Right_Arm,
    ring_one: Bear_Right_Leg,
    ring_two: Bear_Left_Leg,
    trinket: Bear_Left_Arm,
    faith: 'adherent',
    mastery: 'Strength',
    origin: 'Bear',
    sex: findSex(),
    currency: {},
    experience: 0,
    high_score: 0,
    level: 3,
    coordinates: {},
    firewater: {},
    inventory: [],
    maps: [],
    quests: [],
    tutorial: {},
    index: '',
    shareable: '',
    visibiility: '',
    dislikes: [],
    double_dislikes: [],
    likes: []
};