import { Enemy, Equipment } from './GameStore';

function findSex() {
    const chance = Math.floor(Math.random() * 2);
    if (chance === 0) {
        return "Male";
    } else {
        return "Female";
    }

}

const Wolf_Claw: Equipment = {
    name: "Wolf's Paw",
    type: 'Natural',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: 'One Hand',
    attack_type: 'Physical',
    damage_type: ['Slash'],
    physical_damage: 2,
    magical_damage: 0,
    physical_penetration: 1,
    magical_penetration: 0,
    physical_resistance: 0,
    magical_resistance: 0,
    critical_chance: 1,
    critical_damage: 1.01,
    dodge: 0,
    roll: 3,
    constitution: 0,
    strength: 0,
    agility: 2,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Kyn'gi"],
    imgURL: '/images/wolf-claw.png',
    _id: '001'
};

const Wolf_Bite: Equipment = {
    name: "Wolf's Bite",
    type: 'Natural',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: 'One Hand',
    attack_type: 'Physical',
    damage_type: ['Blunt'],
    physical_damage: 3,
    magical_damage: 0,
    physical_penetration: 1,
    magical_penetration: 0,
    physical_resistance: 0,
    magical_resistance: 0,
    critical_chance: 1,
    critical_damage: 1.01,
    dodge: 5,
    roll: 0,
    constitution: 0,
    strength: 0,
    agility: 2,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Kyn'gi"],
    imgURL: '/images/wolf-crunch.png',
    _id: '002'
};

const Wolf_Tear: Equipment = {
    name: "Wolf's Crunchy Chew",
    type: 'Natural',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: 'One Hand',
    attack_type: 'Physical',
    damage_type: ['Pierce'],
    physical_damage: 2,
    magical_damage: 0,
    physical_penetration: 1,
    magical_penetration: 0,
    physical_resistance: 0,
    magical_resistance: 0,
    critical_chance: 1,
    critical_damage: 1.01,
    dodge: 2,
    roll: 2,
    constitution: 0,
    strength: 0,
    agility: 2,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Kyn'gi"],
    imgURL: '/images/wolf-bite.png',
    _id: '003'
};

const Wolf_Tail: Equipment = {
    name: "Wolf's Tail",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2.5,
    magical_resistance: 2.5,
    critical_chance: 3,
    critical_damage: 1.03,
    dodge: 0,
    roll: 2,
    constitution: 0,
    strength: 0,
    agility: 2,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/wolf-tail.png',
    _id: '004'
};

const Wolf_Head: Equipment = {
    name: "Wolf's Head",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2.5,
    magical_resistance: 1.5,
    critical_chance: 3,
    critical_damage: 1.03,
    dodge: 0,
    roll: 2,
    constitution: 1,
    strength: 0,
    agility: 1,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/wolf-head.png',
    _id: '005'
};

const Wolf_Upper_Torso: Equipment = {
    name: "Wolf's Upper Torso",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2.5,
    magical_resistance: 1.5,
    critical_chance: 3,
    critical_damage: 1.03,
    dodge: 0,
    roll: 3,
    constitution: 1,
    strength: 0,
    agility: 1,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/wolf-upper.png',
    _id: '006'
};

const Wolf_Lower_Body: Equipment = {
    name: "Wolf's Lower Body",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2.5,
    magical_resistance: 1.5,
    critical_chance: 3,
    critical_damage: 1.03,
    dodge: 0,
    roll: 3,
    constitution: 1,
    strength: 0,
    agility: 1,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: null,
    imgURL: '/images/wolf-lower.png',
    _id: '007'
};

const Wolf_Leg: Equipment = {
    name: "Wolf's Leg",
    type: 'Leather-Cloth',
    rarity: 'Common',
    itemType: 'Equipment',
    grip: null,
    attack_type: null,
    damage_type: null,
    physical_damage: 1,
    magical_damage: 1,
    physical_penetration: 0,
    magical_penetration: 0,
    physical_resistance: 2,
    magical_resistance: 1,
    critical_chance: 3,
    critical_damage: 1.03,
    dodge: 0,
    roll: 2,
    constitution: 0,
    strength: 0,
    agility: 1,
    achre: 0,
    caeren: 0,
    kyosir: 0,
    influences: ["Kyn'gi"],
    imgURL: '/images/wolf-leg.png',
    _id: '008'
};


export const Wolf: Enemy = {
    name: "Wolf",
    description: "A stray wolf wandering.",
    user: {},
    constitution: 10,
    strength: 10,
    agility: 12,
    achre: 10,
    caeren: 10,
    kyosir: 10,
    named: false,
    type: 'Wolf, Untouched',
    humanoid: false,
    animal: true,
    weapon_one: Wolf_Claw,
    weapon_two: Wolf_Bite,
    weapon_three: Wolf_Tear,
    shield: Wolf_Tail,
    helmet: Wolf_Head,
    chest: Wolf_Upper_Torso,
    legs: Wolf_Lower_Body,
    amulet: Wolf_Leg,
    ring_one: Wolf_Leg,
    ring_two: Wolf_Leg,
    trinket: Wolf_Leg,
    faith: 'adherent',
    mastery: 'Agility',
    origin: 'Wolf',
    sex: findSex(),
    currency: {},
    experience: 0,
    high_score: 0,
    level: 0.5,
    coordinates: {},
    firewater: {},
    inventory: [],
    maps: [],
    quests: [],
    tutorial: {},
    index: '',
    shareable: '',
    visibiility: '',
    dislikes: [],
    double_dislikes: [],
    likes: []
}