export const opponent = {
    "Achreon Druid" : {},
    "Ahn'are Apostle": {},
    "Anashtre": {},
    "Astral Apostle": {},
    "Daethic Inquisitor": {},
    "Daethic Knight": {},
    "Fang Mercenary": {}, 
    "Firesworn": {}, 
    "Fyers Occultist": {},
    "Ilire Occultist": {},
    "Licivitan Soldier": {}, 
    "Ma'ier Occultist": {},
    "Marauder": {}, 
    "Quor'eite Occultist": {},
    "Sedyreal Guard": {},
    "Soverain Blood Cloak": {},
    "Tshaeral Shaman" : {},
}